apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-exporter
  namespace: geostreamdb
  labels:
    app: docker-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-exporter
  template:
    metadata:
      labels:
        app: docker-exporter
    spec:
      containers:
      - name: docker-exporter
        image: ghcr.io/davidborzek/docker-exporter:v0.3.0
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
