apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: geostreamdb-route
  namespace: geostreamdb
spec:
  parentRefs:
    - name: geostreamdb-gateway
      sectionName: http
    - name: geostreamdb-gateway
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway-service
          port: 8080