apiVersion: v1
kind: Service
metadata:
  name: worker-node-service
  namespace: geostreamdb
spec:
  selector:
    app: worker-node
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 2112
    targetPort: 2112
  clusterIP: None  # headless service for direct pod access
