apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: geostreamdb
spec:
  type: NodePort  # TODO: NodePort for local development, LoadBalancer for cloud providers
  selector:
    app: loadbalancer
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30080  # only used if type is NodePort
