apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geostreamdb

resources:
  - ../../k8s
  #- ../../k8s/deployment-docker-exporter.yaml
  #- ../../k8s/service-docker-exporter.yaml

# replace prometheus-config with version that includes docker-exporter scrape job (minikube/Docker runtime only)
#configMapGenerator:
#  - name: prometheus-config
#    behavior: replace
#    files:
#      - prometheus.yml=../../prometheus/prometheus.minikube.yml